# Generated by Django 5.0 on 2023-12-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('document', 'Document'), ('music', 'Music'), ('other', 'Other')], default='other', max_length=40, verbose_name='File Category'),
        ),
    ]
