# Generated by Django 5.0 on 2023-12-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
