# Generated by Django 5.0 on 2023-12-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_download', '0002_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(default='other', max_length=40, verbose_name='File Category'),
        ),
    ]
