# Generated by Django 5.0 on 2023-12-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0005_alter_contact_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
