# Generated by Django 5.0 on 2023-12-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0007_remove_contact_email_remove_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneemail',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='phoneemail',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
    ]
