# Generated by Django 5.0 on 2023-12-15 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0008_remove_phoneemail_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('contact', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='app_contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='app_contacts.contact')),
            ],
        ),
        migrations.DeleteModel(
            name='PhoneEmail',
        ),
    ]
